id = "zed-tempo"
name = "Tempo Language"
version = "0.0.1"
schema_version = 1
authors = ["Viktor Strate Kløvedal <viktorstrate@gmail.com>"]
description = "Tempo choreographic programming language"
repository = "https://github.com/tempo-lang/zed-tempo"

[grammars.tempo]
# repository = "file:///Users/viktorstrate/Cloud/SDU/PhD/repos/tree-sitter-tempo"
repository = "https://github.com/tempo-lang/tree-sitter-tempo"
rev = "597a1205a4112b19258a3903dc7316726e7b69b1"

[language_servers.tempo]
name = "Tempo LSP"
languages = ["Tempo"]
