id = "zed-tempo"
name = "Tempo Language"
version = "0.0.1"
schema_version = 1
authors = ["Viktor Strate Kløvedal <viktorstrate@gmail.com>"]
description = "Tempo choreographic programming language"
repository = "https://github.com/tempo-lang/zed-tempo"

[grammars.tempo]
repository = "https://github.com/tempo-lang/tree-sitter-tempo"
rev = "f64459a8a010aeffdf1a20339e22b0b3bb6cd579"

[language_servers.tempo]
name = "Tempo LSP"
languages = ["Tempo"]
