id = "zed-tempo"
name = "Tempo Language"
version = "0.0.1"
schema_version = 1
authors = ["Viktor Strate Kløvedal <viktorstrate@gmail.com>"]
description = "Tempo choreographic programming language"
repository = "https://github.com/tempo-lang/zed-tempo"

[grammars.tempo]
repository = "https://github.com/tempo-lang/tree-sitter-tempo"
rev = "96d7a73f2dcfd6b1a4daab7ea864829f16ec548b"

[language_servers.tempo]
name = "Tempo LSP"
languages = ["Tempo"]
